services:
  - type: web
    name: senha-wifi-typebot
    env: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: SESSION_SECRET
        generateValue: true
      - key: SPREADSHEET_ID
        sync: false  # Este valor precisa ser configurado pelo usuário
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false  # Este valor precisa ser configurado pelo usuário
      - key: FORCE_DEMO
        value: false
